package com.fd.model;

import java.io.Serializable;

/**
 * Bank Model - Represents a bank entity in the Fixed Deposit system
 * Matches the BANK table structure in Oracle database
 */
public class Bank implements Serializable {
    private static final long serialVersionUID = 1L;
    
    private int bankId;
    private String bankName;
    private String bankAddress;
    private String bankPhone;
    
    // Default Constructor
    public Bank() {
    }
    
    // Constructor for creating a NEW bank (ID is generated by database)
    public Bank(String bankName, String bankAddress, String bankPhone) {
        this.bankName = bankName;
        this.bankAddress = bankAddress;
        this.bankPhone = bankPhone;
    }
    
    // Constructor for FETCHING/UPDATING a bank (Includes the ID)
    public Bank(int bankId, String bankName, String bankAddress, String bankPhone) {
        this.bankId = bankId;
        this.bankName = bankName;
        this.bankAddress = bankAddress;
        this.bankPhone = bankPhone;
    }
    
    // Getters and Setters
    public int getBankId() {
        return bankId;
    }
    
    public void setBankId(int bankId) {
        this.bankId = bankId;
    }
    
    public String getBankName() {
        return bankName;
    }
    
    public void setBankName(String bankName) {
        this.bankName = bankName;
    }
    
    public String getBankAddress() {
        return bankAddress;
    }
    
    public void setBankAddress(String bankAddress) {
        this.bankAddress = bankAddress;
    }
    
    public String getBankPhone() {
        return bankPhone;
    }
    
    public void setBankPhone(String bankPhone) {
        this.bankPhone = bankPhone;
    }
    
    @Override
    public String toString() {
        return "Bank{" +
                "bankId=" + bankId +
                ", bankName='" + bankName + '\'' +
                ", bankAddress='" + bankAddress + '\'' +
                ", bankPhone='" + bankPhone + '\'' +
                '}';
    }
}
