package com.fd.model;

import java.io.Serializable;
import java.util.Objects;

/**
 * Bank Model - Represents a bank entity in the Fixed Deposit system
 * Matches the BANK table structure in Oracle database
 */
public class Bank implements Serializable {
    private static final long serialVersionUID = 1L;
    
    private long bankId;
    private String bankName;
    private String bankAddress;
    private String bankPhone;
    
    // Default Constructor
    public Bank() {
    }
    
    // Constructor for creating a NEW bank (ID is generated by database)
    public Bank(String bankName, String bankAddress, String bankPhone) {
        if (bankName == null || bankName.trim().isEmpty()) {
            throw new IllegalArgumentException("Bank name cannot be null or empty");
        }
        if (bankAddress == null || bankAddress.trim().isEmpty()) {
            throw new IllegalArgumentException("Bank address cannot be null or empty");
        }
        
        this.bankName = bankName;
        this.bankAddress = bankAddress;
        this.bankPhone = bankPhone;
    }
    
    // Constructor for FETCHING/UPDATING a bank (Includes the ID)
    public Bank(long bankId, String bankName, String bankAddress, String bankPhone) {
        if (bankName == null || bankName.trim().isEmpty()) {
            throw new IllegalArgumentException("Bank name cannot be null or empty");
        }
        if (bankAddress == null || bankAddress.trim().isEmpty()) {
            throw new IllegalArgumentException("Bank address cannot be null or empty");
        }
        
        this.bankId = bankId;
        this.bankName = bankName;
        this.bankAddress = bankAddress;
        this.bankPhone = bankPhone;
    }
    
    // Getters and Setters
    public long getBankId() {
        return bankId;
    }
    
    public void setBankId(long bankId) {
        this.bankId = bankId;
    }
    
    public String getBankName() {
        return bankName;
    }
    
    public void setBankName(String bankName) {
        if (bankName == null || bankName.trim().isEmpty()) {
            throw new IllegalArgumentException("Bank name cannot be null or empty");
        }
        this.bankName = bankName;
    }
    
    public String getBankAddress() {
        return bankAddress;
    }
    
    public void setBankAddress(String bankAddress) {
        if (bankAddress == null || bankAddress.trim().isEmpty()) {
            throw new IllegalArgumentException("Bank address cannot be null or empty");
        }
        this.bankAddress = bankAddress;
    }
    
    public String getBankPhone() {
        return bankPhone;
    }
    
    public void setBankPhone(String bankPhone) {
        this.bankPhone = bankPhone;
    }
    
    @Override
    public String toString() {
        return "Bank{" +
                "bankId=" + bankId +
                ", bankName='" + bankName + '\'' +
                ", bankAddress='" + bankAddress + '\'' +
                ", bankPhone='" + bankPhone + '\'' +
                '}';
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Bank bank = (Bank) o;
        return bankId == bank.bankId &&
                Objects.equals(bankName, bank.bankName) &&
                Objects.equals(bankAddress, bank.bankAddress) &&
                Objects.equals(bankPhone, bank.bankPhone);
    }

    @Override
    public int hashCode() {
        return Objects.hash(bankId, bankName, bankAddress, bankPhone);
    }
}
