package com.fd.dao;

import com.fd.model.Bank;
import com.fd.util.DBConnection;
import java.sql.*;
import java.util.ArrayList;
import java.util.List;

/**
 * BankDAO - Data Access Object for Bank operations
 * Handles all database operations for the BANK table
 */
public class BankDAO {
    
    /**
     * Insert a new bank into the database
     * Bank ID is auto-generated by IDENTITY column (not sequence)
     */
    public boolean insertBank(Bank bank) {
        // Don't specify BANKID - it's auto-generated by IDENTITY column
        String query = "INSERT INTO BANK (BANKNAME, BANKADDRESS, BANKPHONE) " +
                       "VALUES (?, ?, ?)";
        
        System.out.println("========================================");
        System.out.println("💾 BankDAO: Inserting new bank");
        System.out.println("   Name: " + bank.getBankName());
        
        try (Connection conn = DBConnection.getConnection();
             PreparedStatement pstmt = conn.prepareStatement(query)) {
            
            pstmt.setString(1, bank.getBankName());
            pstmt.setString(2, bank.getBankAddress());
            pstmt.setString(3, bank.getBankPhone());
            
            int rowsAffected = pstmt.executeUpdate();
            
            if (rowsAffected > 0) {
                System.out.println("✅ Bank inserted successfully");
                System.out.println("========================================");
                return true;
            } else {
                System.err.println("❌ No rows inserted");
                System.out.println("========================================");
                return false;
            }
            
        } catch (SQLException e) {
            System.err.println("❌ Error inserting bank: " + e.getMessage());
            e.printStackTrace();
            System.out.println("========================================");
            return false;
        }
    }
    
    /**
     * Get all banks from the database
     * Ordered by BANKID descending (newest first)
     */
    public List<Bank> getAllBanks() {
        List<Bank> banks = new ArrayList<>();
        String query = "SELECT BANKID, BANKNAME, BANKADDRESS, BANKPHONE " +
                       "FROM BANK ORDER BY BANKID DESC";
        
        System.out.println("========================================");
        System.out.println("🔍 BankDAO: Fetching all banks");
        
        try (Connection conn = DBConnection.getConnection();
             PreparedStatement pstmt = conn.prepareStatement(query);
             ResultSet rs = pstmt.executeQuery()) {
            
            while (rs.next()) {
                Bank bank = new Bank(
                    rs.getInt("BANKID"),
                    rs.getString("BANKNAME"),
                    rs.getString("BANKADDRESS"),
                    rs.getString("BANKPHONE")
                );
                banks.add(bank);
            }
            
            System.out.println("✅ Retrieved " + banks.size() + " banks");
            System.out.println("========================================");
            
        } catch (SQLException e) {
            System.err.println("❌ Error fetching banks: " + e.getMessage());
            e.printStackTrace();
            System.out.println("========================================");
        }
        
        return banks;
    }
    
    /**
     * Get a specific bank by ID
     */
    public Bank getBankById(int bankId) {
        Bank bank = null;
        String query = "SELECT BANKID, BANKNAME, BANKADDRESS, BANKPHONE " +
                       "FROM BANK WHERE BANKID = ?";
        
        System.out.println("========================================");
        System.out.println("🔍 BankDAO: Fetching bank by ID: " + bankId);
        
        try (Connection conn = DBConnection.getConnection();
             PreparedStatement pstmt = conn.prepareStatement(query)) {
            
            pstmt.setInt(1, bankId);
            
            try (ResultSet rs = pstmt.executeQuery()) {
                if (rs.next()) {
                    bank = new Bank(
                        rs.getInt("BANKID"),
                        rs.getString("BANKNAME"),
                        rs.getString("BANKADDRESS"),
                        rs.getString("BANKPHONE")
                    );
                    System.out.println("✅ Bank found: " + bank.getBankName());
                } else {
                    System.out.println("❌ No bank found with ID: " + bankId);
                }
            }
            
            System.out.println("========================================");
            
        } catch (SQLException e) {
            System.err.println("❌ Error fetching bank: " + e.getMessage());
            e.printStackTrace();
            System.out.println("========================================");
        }
        
        return bank;
    }
    
    /**
     * Update bank information (phone and address only)
     * Bank name cannot be changed
     */
    public boolean updateBank(Bank bank) {
        String query = "UPDATE BANK SET BANKADDRESS = ?, BANKPHONE = ? WHERE BANKID = ?";
        
        System.out.println("========================================");
        System.out.println("💾 BankDAO: Updating bank");
        System.out.println("   Bank ID: " + bank.getBankId());
        System.out.println("   Name: " + bank.getBankName());
        
        try (Connection conn = DBConnection.getConnection();
             PreparedStatement pstmt = conn.prepareStatement(query)) {
            
            pstmt.setString(1, bank.getBankAddress());
            pstmt.setString(2, bank.getBankPhone());
            pstmt.setInt(3, bank.getBankId());
            
            int rowsAffected = pstmt.executeUpdate();
            
            if (rowsAffected > 0) {
                System.out.println("✅ Bank updated successfully");
                System.out.println("========================================");
                return true;
            } else {
                System.err.println("❌ No rows updated - Bank ID not found?");
                System.out.println("========================================");
                return false;
            }
            
        } catch (SQLException e) {
            System.err.println("❌ Error updating bank: " + e.getMessage());
            e.printStackTrace();
            System.out.println("========================================");
            return false;
        }
    }
    
    /**
     * Delete a bank by ID
     * Optional - only implement if needed
     */
    public boolean deleteBank(int bankId) {
        String query = "DELETE FROM BANK WHERE BANKID = ?";
        
        System.out.println("========================================");
        System.out.println("🗑️ BankDAO: Deleting bank ID: " + bankId);
        
        try (Connection conn = DBConnection.getConnection();
             PreparedStatement pstmt = conn.prepareStatement(query)) {
            
            pstmt.setInt(1, bankId);
            
            int rowsAffected = pstmt.executeUpdate();
            
            if (rowsAffected > 0) {
                System.out.println("✅ Bank deleted successfully");
                System.out.println("========================================");
                return true;
            } else {
                System.err.println("❌ No rows deleted - Bank ID not found?");
                System.out.println("========================================");
                return false;
            }
            
        } catch (SQLException e) {
            System.err.println("❌ Error deleting bank: " + e.getMessage());
            e.printStackTrace();
            System.out.println("========================================");
            return false;
        }
    }
    
    /**
     * Check if a bank name already exists
     * Useful for preventing duplicates
     */
    public boolean bankNameExists(String bankName) {
        String query = "SELECT COUNT(*) FROM BANK WHERE LOWER(BANKNAME) = LOWER(?)";
        
        try (Connection conn = DBConnection.getConnection();
             PreparedStatement pstmt = conn.prepareStatement(query)) {
            
            pstmt.setString(1, bankName.trim());
            
            try (ResultSet rs = pstmt.executeQuery()) {
                if (rs.next()) {
                    int count = rs.getInt(1);
                    return count > 0;
                }
            }
            
        } catch (SQLException e) {
            System.err.println("❌ Error checking bank name: " + e.getMessage());
            e.printStackTrace();
        }
        
        return false;
    }
}
