package com.fd.dao;

import com.fd.model.Bank;
import com.fd.util.DBConnection;
import java.sql.*;
import java.util.ArrayList;
import java.util.List;

/**
 * BankDAO - Data Access Object for Bank operations
 * Handles all database operations for the BANK table
 */
public class BankDAO {

    // Helper method for database connection and query execution
    private static boolean executeUpdate(String query, Object... params) {
        try (Connection conn = DBConnection.getConnection();
             PreparedStatement pstmt = conn.prepareStatement(query)) {
            
            // Set parameters dynamically
            for (int i = 0; i < params.length; i++) {
                pstmt.setObject(i + 1, params[i]);
            }
            
            int rowsAffected = pstmt.executeUpdate();
            return rowsAffected > 0;
        } catch (SQLException e) {
            System.err.println("❌ Error executing update: " + e.getMessage());
            e.printStackTrace();
            return false;
        }
    }
    
    /**
     * Insert a new bank into the database
     * Bank ID is auto-generated by SERIAL column in PostgreSQL
     */
    public boolean insertBank(Bank bank) {
        String query = "INSERT INTO BANK (BANKNAME, BANKADDRESS, BANKPHONE) VALUES (?, ?, ?)";
        
        System.out.println("========================================");
        System.out.println("💾 BankDAO: Inserting new bank");
        System.out.println("   Name: " + bank.getBankName());
        
        return executeUpdate(query, bank.getBankName(), bank.getBankAddress(), bank.getBankPhone());
    }
    
    /**
     * Get all banks from the database
     * Ordered by BANKID descending (newest first)
     */
    public List<Bank> getAllBanks() {
        List<Bank> banks = new ArrayList<>();
        String query = "SELECT BANKID, BANKNAME, BANKADDRESS, BANKPHONE FROM BANK ORDER BY BANKID DESC";
        
        System.out.println("========================================");
        System.out.println("🔍 BankDAO: Fetching all banks");
        
        try (Connection conn = DBConnection.getConnection();
             PreparedStatement pstmt = conn.prepareStatement(query);
             ResultSet rs = pstmt.executeQuery()) {
            
            while (rs.next()) {
                Bank bank = new Bank(
                    rs.getLong("BANKID"),  // PostgreSQL uses BIGINT, hence `long`
                    rs.getString("BANKNAME"),
                    rs.getString("BANKADDRESS"),
                    rs.getString("BANKPHONE")
                );
                banks.add(bank);
            }
            
            System.out.println("✅ Retrieved " + banks.size() + " banks");
            return banks;
            
        } catch (SQLException e) {
            System.err.println("❌ Error fetching banks: " + e.getMessage());
            e.printStackTrace();
            return banks;  // Return empty list in case of error
        }
    }
    
    /**
     * Get a specific bank by ID
     */
    public Bank getBankById(long bankId) {  // Changed to long for PostgreSQL compatibility
        Bank bank = null;
        String query = "SELECT BANKID, BANKNAME, BANKADDRESS, BANKPHONE FROM BANK WHERE BANKID = ?";
        
        System.out.println("========================================");
        System.out.println("🔍 BankDAO: Fetching bank by ID: " + bankId);
        
        try (Connection conn = DBConnection.getConnection();
             PreparedStatement pstmt = conn.prepareStatement(query)) {
            
            pstmt.setLong(1, bankId);  // PostgreSQL uses long (BIGINT)
            
            try (ResultSet rs = pstmt.executeQuery()) {
                if (rs.next()) {
                    bank = new Bank(
                        rs.getLong("BANKID"),  // PostgreSQL uses BIGINT
                        rs.getString("BANKNAME"),
                        rs.getString("BANKADDRESS"),
                        rs.getString("BANKPHONE")
                    );
                    System.out.println("✅ Bank found: " + bank.getBankName());
                } else {
                    System.out.println("❌ No bank found with ID: " + bankId);
                }
            }
            
        } catch (SQLException e) {
            System.err.println("❌ Error fetching bank: " + e.getMessage());
            e.printStackTrace();
        }
        
        return bank;
    }
    
    /**
     * Update bank information (phone and address only)
     * Bank name cannot be changed
     */
    public boolean updateBank(Bank bank) {
        String query = "UPDATE BANK SET BANKADDRESS = ?, BANKPHONE = ? WHERE BANKID = ?";
        
        System.out.println("========================================");
        System.out.println("💾 BankDAO: Updating bank");
        System.out.println("   Bank ID: " + bank.getBankId());
        
        return executeUpdate(query, bank.getBankAddress(), bank.getBankPhone(), bank.getBankId());
    }
    
    /**
     * Delete a bank by ID
     * Optional - only implement if needed
     */
    public boolean deleteBank(long bankId) {  // Changed to long
        String query = "DELETE FROM BANK WHERE BANKID = ?";
        
        System.out.println("========================================");
        System.out.println("🗑️ BankDAO: Deleting bank ID: " + bankId);
        
        return executeUpdate(query, bankId);
    }
    
    /**
     * Check if a bank name already exists
     * Useful for preventing duplicates
     */
    public boolean bankNameExists(String bankName) {
        String query = "SELECT COUNT(*) FROM BANK WHERE LOWER(BANKNAME) = LOWER(?)";
        
        try (Connection conn = DBConnection.getConnection();
             PreparedStatement pstmt = conn.prepareStatement(query)) {
            
            pstmt.setString(1, bankName.trim());
            
            try (ResultSet rs = pstmt.executeQuery()) {
                if (rs.next()) {
                    int count = rs.getInt(1);
                    return count > 0;
                }
            }
            
        } catch (SQLException e) {
            System.err.println("❌ Error checking bank name: " + e.getMessage());
            e.printStackTrace();
        }
        
        return false;
    }
}
